### ISSUE TITLE
Remover duplicacao de codigo

### ISSUE THREAD

**Issue by tcanabrava** [KarinaPassos/cmaismais#1]
https://github.com/KarinaPassos/cmaismais/blob/da4e9bc673968e0075331a956d6cece27500691f/linkedList/main.cpp#L52
Ce nao concorda que aqui esse if () { ... return } else { return } voce pode tirar o else e o return do if e fazer if (...) {} 
e na linha seguinte return; ?

**Comment by KarinaPassos** [comment]
verdade heheheh
