### ISSUE TITLE
Acertar Polimorfismo

### ISSUE THREAD

**Issue by tcanabrava** [KarinaPassos/cmaismais#2]
https://github.com/KarinaPassos/cmaismais/blob/da4e9bc673968e0075331a956d6cece27500691f/FormaGeometrica/main.cpp#L9

Nessa linha voce nao esta utilizando polimorfismo.
Polimorfismo acontece quando voce tem um objeto base chamando as coisas do objeto filho.
por exemplo

FiguraGeometrica *g = new Quadrado();
FiguraGeometrica *t = new Triangulo();

Os objetos que se trabalham em polimorfismo sao sempre os objetos pai, que tem acesso aos comportamentos dos filhos por causa dos metodos virtuais.l

**Comment by KarinaPassos** [comment]
feito heheh
